apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: previews
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/nishit93-hub/argocd-previews.git
    targetRevision: master
    path: helm
  destination:
    server: https://kubernetes.default.svc
    namespace: previews
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
